[versions]
agp = "8.13.1"
kotlin = "2.2.21"
playServicesWearable = "19.0.0"
wearCompose = "1.5.5"
wearToolingPreview = "1.0.0"
tiles = "1.5.0"
protolayout = "1.3.0"
horologist = "0.7.15"
watchfaceComplicationsDataSourceKtx = "1.2.1"
coil = "3.3.0"

[libraries]
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2025.11.01" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-material = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "wearCompose" }
compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "wearCompose" }
wear-tooling-preview = { group = "androidx.wear", name = "wear-tooling-preview", version.ref = "wearToolingPreview" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.12.0" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version = "1.2.0" }
tiles = { group = "androidx.wear.tiles", name = "tiles", version.ref = "tiles" }
tiles-material = { group = "androidx.wear.tiles", name = "tiles-material", version.ref = "tiles" }
tiles-tooling = { group = "androidx.wear.tiles", name = "tiles-tooling", version.ref = "tiles" }
tiles-tooling-preview = { group = "androidx.wear.tiles", name = "tiles-tooling-preview", version.ref = "tiles" }
protolayout = { module = "androidx.wear.protolayout:protolayout", version.ref = "protolayout" }
protolayoutMaterial3 = { module = "androidx.wear.protolayout:protolayout-material3", version.ref = "protolayout" }
horologistComposeTools = { group = "com.google.android.horologist", name = "horologist-compose-tools", version.ref = "horologist" }
horologistTiles = { group = "com.google.android.horologist", name = "horologist-tiles", version.ref = "horologist" }
horologistComposeLayout = { group = "com.google.android.horologist", name = "horologist-compose-layout", version.ref = "horologist" }
watchface-complications-data-source-ktx = { group = "androidx.wear.watchface", name = "watchface-complications-data-source-ktx", version.ref = "watchfaceComplicationsDataSourceKtx" }
kotlinxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.8.1" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version = "5.3.2" }
qrcodeKotlin = { group = "io.github.g0dkar", name = "qrcode-kotlin", version = "4.5.0" }
coilCompose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coilNetworkOkhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
